package fr.jambar.gsg.model.entity;

// Generated 28 mars 2016 15:16:45 by Hibernate Tools 3.4.0.CR1

/**
 * Gsgcategories generated by hbm2java
 */
public class Gsgcategories implements java.io.Serializable {

	private long idCat;
	private String code;
	private String libelle;

	public Gsgcategories() {
	}

	public Gsgcategories(long idCat) {
		this.idCat = idCat;
	}

	public Gsgcategories(long idCat, String code, String libelle) {
		this.idCat = idCat;
		this.code = code;
		this.libelle = libelle;
	}

	public long getIdCat() {
		return this.idCat;
	}

	public void setIdCat(long idCat) {
		this.idCat = idCat;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
