package fr.jambar.gsg.model.entity;

// Generated 28 mars 2016 15:16:45 by Hibernate Tools 3.4.0.CR1

/**
 * Gsggenre generated by hbm2java
 */
public class Gsggenre implements java.io.Serializable {

	private long idGenre;
	private String code;
	private String libelle;

	public Gsggenre() {
	}

	public Gsggenre(long idGenre) {
		this.idGenre = idGenre;
	}

	public Gsggenre(long idGenre, String code, String libelle) {
		this.idGenre = idGenre;
		this.code = code;
		this.libelle = libelle;
	}

	public long getIdGenre() {
		return this.idGenre;
	}

	public void setIdGenre(long idGenre) {
		this.idGenre = idGenre;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
