package fr.jambar.gsg.model.entity;

// Generated 28 mars 2016 15:16:45 by Hibernate Tools 3.4.0.CR1

/**
 * GsglignesoperationId generated by hbm2java
 */
public class GsglignesoperationId implements java.io.Serializable {

	private long idOp;
	private long idProd;
	private int idLop;

	public GsglignesoperationId() {
	}

	public GsglignesoperationId(long idOp, long idProd, int idLop) {
		this.idOp = idOp;
		this.idProd = idProd;
		this.idLop = idLop;
	}

	public long getIdOp() {
		return this.idOp;
	}

	public void setIdOp(long idOp) {
		this.idOp = idOp;
	}

	public long getIdProd() {
		return this.idProd;
	}

	public void setIdProd(long idProd) {
		this.idProd = idProd;
	}

	public int getIdLop() {
		return this.idLop;
	}

	public void setIdLop(int idLop) {
		this.idLop = idLop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GsglignesoperationId))
			return false;
		GsglignesoperationId castOther = (GsglignesoperationId) other;

		return (this.getIdOp() == castOther.getIdOp())
				&& (this.getIdProd() == castOther.getIdProd())
				&& (this.getIdLop() == castOther.getIdLop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdOp();
		result = 37 * result + (int) this.getIdProd();
		result = 37 * result + this.getIdLop();
		return result;
	}

}
