package fr.jambar.gsg.model.entity;

// Generated 28 mars 2016 15:16:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Gsglignesoperation generated by hbm2java
 */
public class Gsglignesoperation implements java.io.Serializable {

	private GsglignesoperationId id;
	private Gsgoperations gsgoperations;
	private Long montant;
	private Date dateCreation;
	private Date dateMaj;
	private Integer qte;

	public Gsglignesoperation() {
	}

	public Gsglignesoperation(GsglignesoperationId id,
			Gsgoperations gsgoperations) {
		this.id = id;
		this.gsgoperations = gsgoperations;
	}

	public Gsglignesoperation(GsglignesoperationId id,
			Gsgoperations gsgoperations, Long montant, Date dateCreation,
			Date dateMaj, Integer qte) {
		this.id = id;
		this.gsgoperations = gsgoperations;
		this.montant = montant;
		this.dateCreation = dateCreation;
		this.dateMaj = dateMaj;
		this.qte = qte;
	}

	public GsglignesoperationId getId() {
		return this.id;
	}

	public void setId(GsglignesoperationId id) {
		this.id = id;
	}

	public Gsgoperations getGsgoperations() {
		return this.gsgoperations;
	}

	public void setGsgoperations(Gsgoperations gsgoperations) {
		this.gsgoperations = gsgoperations;
	}

	public Long getMontant() {
		return this.montant;
	}

	public void setMontant(Long montant) {
		this.montant = montant;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Date getDateMaj() {
		return this.dateMaj;
	}

	public void setDateMaj(Date dateMaj) {
		this.dateMaj = dateMaj;
	}

	public Integer getQte() {
		return this.qte;
	}

	public void setQte(Integer qte) {
		this.qte = qte;
	}

}
