package fr.jambar.gsg.model.entity;

// Generated 28 mars 2016 15:16:45 by Hibernate Tools 3.4.0.CR1

/**
 * Gsgmarque generated by hbm2java
 */
public class Gsgmarque implements java.io.Serializable {

	private long idMaque;
	private String code;
	private String libelle;

	public Gsgmarque() {
	}

	public Gsgmarque(long idMaque) {
		this.idMaque = idMaque;
	}

	public Gsgmarque(long idMaque, String code, String libelle) {
		this.idMaque = idMaque;
		this.code = code;
		this.libelle = libelle;
	}

	public long getIdMaque() {
		return this.idMaque;
	}

	public void setIdMaque(long idMaque) {
		this.idMaque = idMaque;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
