package fr.jambar.gsg.model.entity;

// Generated 28 mars 2016 15:16:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gsgoperations generated by hbm2java
 */
public class Gsgoperations implements java.io.Serializable {

	private long idOp;
	private Integer idMr;
	private String toCode;
	private Long idPerson;
	private String numero;
	private Date date;
	private Long montantTotal;
	private Long remise;
	private Set<Gsglignesoperation> gsglignesoperations = new HashSet<Gsglignesoperation>(
			0);

	public Gsgoperations() {
	}

	public Gsgoperations(long idOp) {
		this.idOp = idOp;
	}

	public Gsgoperations(long idOp, Integer idMr, String toCode, Long idPerson,
			String numero, Date date, Long montantTotal, Long remise,
			Set<Gsglignesoperation> gsglignesoperations) {
		this.idOp = idOp;
		this.idMr = idMr;
		this.toCode = toCode;
		this.idPerson = idPerson;
		this.numero = numero;
		this.date = date;
		this.montantTotal = montantTotal;
		this.remise = remise;
		this.gsglignesoperations = gsglignesoperations;
	}

	public long getIdOp() {
		return this.idOp;
	}

	public void setIdOp(long idOp) {
		this.idOp = idOp;
	}

	public Integer getIdMr() {
		return this.idMr;
	}

	public void setIdMr(Integer idMr) {
		this.idMr = idMr;
	}

	public String getToCode() {
		return this.toCode;
	}

	public void setToCode(String toCode) {
		this.toCode = toCode;
	}

	public Long getIdPerson() {
		return this.idPerson;
	}

	public void setIdPerson(Long idPerson) {
		this.idPerson = idPerson;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Long getMontantTotal() {
		return this.montantTotal;
	}

	public void setMontantTotal(Long montantTotal) {
		this.montantTotal = montantTotal;
	}

	public Long getRemise() {
		return this.remise;
	}

	public void setRemise(Long remise) {
		this.remise = remise;
	}

	public Set<Gsglignesoperation> getGsglignesoperations() {
		return this.gsglignesoperations;
	}

	public void setGsglignesoperations(
			Set<Gsglignesoperation> gsglignesoperations) {
		this.gsglignesoperations = gsglignesoperations;
	}

}
