package fr.jambar.gsg.model.entity;

// Generated 28 mars 2016 15:16:45 by Hibernate Tools 3.4.0.CR1

/**
 * GsgpiecesId generated by hbm2java
 */
public class GsgpiecesId implements java.io.Serializable {

	private long idProd;
	private int idPiece;

	public GsgpiecesId() {
	}

	public GsgpiecesId(long idProd, int idPiece) {
		this.idProd = idProd;
		this.idPiece = idPiece;
	}

	public long getIdProd() {
		return this.idProd;
	}

	public void setIdProd(long idProd) {
		this.idProd = idProd;
	}

	public int getIdPiece() {
		return this.idPiece;
	}

	public void setIdPiece(int idPiece) {
		this.idPiece = idPiece;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GsgpiecesId))
			return false;
		GsgpiecesId castOther = (GsgpiecesId) other;

		return (this.getIdProd() == castOther.getIdProd())
				&& (this.getIdPiece() == castOther.getIdPiece());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdProd();
		result = 37 * result + this.getIdPiece();
		return result;
	}

}
