package fr.jambar.gsg.model.entity;

// Generated 28 mars 2016 15:16:45 by Hibernate Tools 3.4.0.CR1

/**
 * Gsgpersonnephysique generated by hbm2java
 */
public class Gsgpersonnephysique implements java.io.Serializable {

	private GsgpersonnephysiqueId id;
	private String nom;
	private String prenom;

	public Gsgpersonnephysique() {
	}

	public Gsgpersonnephysique(GsgpersonnephysiqueId id) {
		this.id = id;
	}

	public Gsgpersonnephysique(GsgpersonnephysiqueId id, String nom,
			String prenom) {
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
	}

	public GsgpersonnephysiqueId getId() {
		return this.id;
	}

	public void setId(GsgpersonnephysiqueId id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

}
