package fr.jambar.gsg.model.entity;

// Generated 28 mars 2016 15:16:45 by Hibernate Tools 3.4.0.CR1

/**
 * Gsgpersonnemorale generated by hbm2java
 */
public class Gsgpersonnemorale implements java.io.Serializable {

	private GsgpersonnemoraleId id;
	private Integer raisonSociale;

	public Gsgpersonnemorale() {
	}

	public Gsgpersonnemorale(GsgpersonnemoraleId id) {
		this.id = id;
	}

	public Gsgpersonnemorale(GsgpersonnemoraleId id, Integer raisonSociale) {
		this.id = id;
		this.raisonSociale = raisonSociale;
	}

	public GsgpersonnemoraleId getId() {
		return this.id;
	}

	public void setId(GsgpersonnemoraleId id) {
		this.id = id;
	}

	public Integer getRaisonSociale() {
		return this.raisonSociale;
	}

	public void setRaisonSociale(Integer raisonSociale) {
		this.raisonSociale = raisonSociale;
	}

}
