package fr.jambar.gsg.model.entity;

// Generated 28 mars 2016 15:16:45 by Hibernate Tools 3.4.0.CR1

/**
 * GsgpersonnephysiqueId generated by hbm2java
 */
public class GsgpersonnephysiqueId implements java.io.Serializable {

	private long idPerson;
	private int idPp;

	public GsgpersonnephysiqueId() {
	}

	public GsgpersonnephysiqueId(long idPerson, int idPp) {
		this.idPerson = idPerson;
		this.idPp = idPp;
	}

	public long getIdPerson() {
		return this.idPerson;
	}

	public void setIdPerson(long idPerson) {
		this.idPerson = idPerson;
	}

	public int getIdPp() {
		return this.idPp;
	}

	public void setIdPp(int idPp) {
		this.idPp = idPp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GsgpersonnephysiqueId))
			return false;
		GsgpersonnephysiqueId castOther = (GsgpersonnephysiqueId) other;

		return (this.getIdPerson() == castOther.getIdPerson())
				&& (this.getIdPp() == castOther.getIdPp());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdPerson();
		result = 37 * result + this.getIdPp();
		return result;
	}

}
