package fr.jambar.gsg.model.entity;

// Generated 28 mars 2016 15:16:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Gsgpieces generated by hbm2java
 */
public class Gsgpieces implements java.io.Serializable {

	private GsgpiecesId id;
	private Date dateFabric;
	private Date datePutil;
	private Date dateAcquisition;

	public Gsgpieces() {
	}

	public Gsgpieces(GsgpiecesId id) {
		this.id = id;
	}

	public Gsgpieces(GsgpiecesId id, Date dateFabric, Date datePutil,
			Date dateAcquisition) {
		this.id = id;
		this.dateFabric = dateFabric;
		this.datePutil = datePutil;
		this.dateAcquisition = dateAcquisition;
	}

	public GsgpiecesId getId() {
		return this.id;
	}

	public void setId(GsgpiecesId id) {
		this.id = id;
	}

	public Date getDateFabric() {
		return this.dateFabric;
	}

	public void setDateFabric(Date dateFabric) {
		this.dateFabric = dateFabric;
	}

	public Date getDatePutil() {
		return this.datePutil;
	}

	public void setDatePutil(Date datePutil) {
		this.datePutil = datePutil;
	}

	public Date getDateAcquisition() {
		return this.dateAcquisition;
	}

	public void setDateAcquisition(Date dateAcquisition) {
		this.dateAcquisition = dateAcquisition;
	}

}
