package fr.jambar.gsg.model.entity;

// Generated 28 mars 2016 15:16:45 by Hibernate Tools 3.4.0.CR1

/**
 * Gsgtypeoperations generated by hbm2java
 */
public class Gsgtypeoperations implements java.io.Serializable {

	private String toCode;
	private String toLibelle;
	private String toDescription;

	public Gsgtypeoperations() {
	}

	public Gsgtypeoperations(String toCode) {
		this.toCode = toCode;
	}

	public Gsgtypeoperations(String toCode, String toLibelle,
			String toDescription) {
		this.toCode = toCode;
		this.toLibelle = toLibelle;
		this.toDescription = toDescription;
	}

	public String getToCode() {
		return this.toCode;
	}

	public void setToCode(String toCode) {
		this.toCode = toCode;
	}

	public String getToLibelle() {
		return this.toLibelle;
	}

	public void setToLibelle(String toLibelle) {
		this.toLibelle = toLibelle;
	}

	public String getToDescription() {
		return this.toDescription;
	}

	public void setToDescription(String toDescription) {
		this.toDescription = toDescription;
	}

}
