package fr.jambar.gsg.model.entity;

// Generated 28 mars 2016 15:16:45 by Hibernate Tools 3.4.0.CR1

/**
 * GsgvehiculesId generated by hbm2java
 */
public class GsgvehiculesId implements java.io.Serializable {

	private long idProd;
	private long idVehicules;

	public GsgvehiculesId() {
	}

	public GsgvehiculesId(long idProd, long idVehicules) {
		this.idProd = idProd;
		this.idVehicules = idVehicules;
	}

	public long getIdProd() {
		return this.idProd;
	}

	public void setIdProd(long idProd) {
		this.idProd = idProd;
	}

	public long getIdVehicules() {
		return this.idVehicules;
	}

	public void setIdVehicules(long idVehicules) {
		this.idVehicules = idVehicules;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GsgvehiculesId))
			return false;
		GsgvehiculesId castOther = (GsgvehiculesId) other;

		return (this.getIdProd() == castOther.getIdProd())
				&& (this.getIdVehicules() == castOther.getIdVehicules());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdProd();
		result = 37 * result + (int) this.getIdVehicules();
		return result;
	}

}
